# Generated by Django 3.0.5 on 2020-04-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaLS', '0002_auto_20200422_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='emoji',
            field=models.IntegerField(),
        ),
    ]
