# Generated by Django 3.0.5 on 2020-04-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment_1_7420_ls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
